osx_image: xcode10
language: objective-c
stage: Build
env:
  matrix:
  - TARGET="ParseSwift (macOS)" 
  - TARGET="ParseSwift (iOS)" 
script: set -o pipefail && xcodebuild -target "$TARGET" | xcpretty

jobs:
  include:
    - stage: package managers
      env: Swift Pacakge Manager
      script: 
        - swift build
        - swift test 
    - stage: package managers
      env: Cocoapods
      script: pod lib lint --verbose
    - stage: package managers
      env: Carthage
      script: carthage build --no-skip-current

